### PR TITLE
added requirements.txt

### PR DESCRIPTION
**Pull request by tralfamadude**
Here is a requirements.txt that works for me.

### CODE REVIEW

**Comment by aigagror** [comment]
There are many modules listed here that are not used in this repo. Please fix this.

**Comment by tralfamadude** [comment]
Well that's what 'pip freeze' emitted; perhaps some are contingent requirements, I did not add any excess packages. 

The image aka PIL aka Pillow one was tricky. I ended up using 'pip install image' which mentioned Pillow while it was happening.

**Comment by aigagror** [comment]
Oh I see. So it's adding packages that are needed by the ones that are imported. I think I'd rather just list the high level packages needed like pytorch, numpy, PIL etc. I also don't like the idea of having specific package versions as well. I'll add it to the README

**Comment by aigagror** [comment]
Done: 2fc818c60b33a65933d66038ef0597375d17f313

**Pull request closed without merging**
